version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: yarn run start_dev
    networks:
      - default
    ports:
      - '3000:3000'
networks:
  default:
    external:
      name: dev
volumes:
  node_modules: