var express = require('express');
var router = express.Router();

const account = require('../components/account');
const applications = require('../components/applications');
const applications_v2 = require('../components/applications_v2');
const group = require('../components/group');
const inf = require('../components/infrastructure');
const integration = require('../components/integration');
const jira = require('../components/jira');
const job = require('../components/job');
const logmetric = require('../components/logmetric');
const providers_v2 = require('../components/providers_v2');
const database = require('../components/database');
const database_v3 = require('../controllers/database');
const provider_v3 = require('../controllers/provider');
const jenkins = require('../controllers/jenkins');
const user = require('../components/user');
const utilities = require('../components/utilities');
const audit = require('../controllers/audit');
const serviceAccount = require('../components/service_account');
const sslTls = require('../components/ssl_tls');
const environment_v2 = require('../controllers/environment');
const application_v3 = require('../controllers/application');
const sslTls_v2 = require('../controllers/ssl_tls');
const inf_v2 = require('../controllers/infrastructure');
const logmetric_v3 = require('../controllers/logmetric');
const terraform_module = require('../controllers/terraform_module');
const utopiops_application = require('../controllers/utopiops_application');
const kubernetes = require('../controllers/kubernetes');
const elasticacheRedis = require('../controllers/elasticache_redis');
const domain = require('../controllers/domain');
const accessToken = require('../controllers/access_token');
const { getAccountDetails } = require('../middlewares/getAccountDetails');

router.use('/v2/ssl_tls', getAccountDetails, sslTls_v2);
router.use('/applications/utopiops', getAccountDetails, utopiops_application);
router.use('/v3/applications', getAccountDetails, application_v3);
router.use('/v3/environment', getAccountDetails, environment_v2);
router.use('/v3/database', getAccountDetails, database_v3);
router.use('/v3/provider', getAccountDetails, provider_v3);
router.use('/audit', getAccountDetails, audit);
router.use('/v2/inf', getAccountDetails, inf_v2);
router.use('/terraform-module', getAccountDetails, terraform_module);
router.use('/v2/applications', applications_v2);
router.use('/v2/provider', providers_v2);
router.use('/v2/database', database);
router.use('/applications', applications);
router.use('/account', account);
router.use('/group', getAccountDetails, group);
router.use('/integration', getAccountDetails, integration);
router.use('/inf', inf);
router.use('/jenkins', jenkins);
router.use('/jira', jira);
router.use('/job', getAccountDetails, job);
router.use('/utilities', getAccountDetails, utilities);
router.use('/user', getAccountDetails, user);
router.use('/logmetric', logmetric);
router.use('/v3/logmetric', getAccountDetails, logmetric_v3);
router.use('/service-account', getAccountDetails, serviceAccount);
router.use('/ssl_tls', sslTls);
router.use('/kubernetes', getAccountDetails, kubernetes);
router.use('/elasticache/redis', getAccountDetails, elasticacheRedis);
router.use('/domain', getAccountDetails, domain);
router.use('/access-token', getAccountDetails, accessToken);
module.exports = router;
